refine: make warning and error messages consistent

diff --git a/tde b/tde
--- a/tde
+++ b/tde
@@ -141,7 +141,11 @@ PROJECT_DIRS=()
 PROJECT_DEFS=() # Project workspaces (options and workspace directory)
 
 write_error_msg() {
-    echo "$(basename "$0"): $1" >&2
+    echo "$(basename "$0"): error: $1" >&2
+}
+
+write_warning_msg() {
+    echo "$(basename "$0"): warning: $1" >&2
 }
 
 write_verbose_message() {
@@ -192,16 +196,16 @@ attach_session() {
         client_count=$(attached_client_count "$session_name")
         if [[ $client_count -ne 0 ]]; then
             local msg
-            msg="warning: tmux session '$session_name' is attached to $client_count other client terminal"
+            msg="tmux session '$session_name' is attached to $client_count other client terminal"
             if [[ $client_count -ne 1 ]]; then
                 msg="${msg}s"
             fi
-            write_error_msg "$msg"
+            write_warning_msg "$msg"
         fi
         tmux_cmd attach-session -t "$session_name"
         return
     fi
-    write_error_msg "warning: refusing to attach nested tmux session '$session_name' inside tmux session '$(current_session)'"
+    write_warning_msg "refusing to attach nested tmux session '$session_name' inside tmux session '$(current_session)'"
 }
 
 # Print or execute tmux commands
@@ -539,7 +543,7 @@ for index in "${!PROJECT_DEFS[@]}"; do
         fi
     else
         if grep -Fxq "$WIN_NAME" <<<"$EXISTING_WINDOWS"; then
-            write_error_msg "duplicate project workspace name: '$WIN_NAME' exists in session '$SESSION_NAME', skipping"
+            write_warning_msg "duplicate project workspace name: '$WIN_NAME' exists in session '$SESSION_NAME', skipping"
             continue
         fi
         tmux_cmd new-window -t "$SESSION_NAME:" -c "$dir" -n "$WIN_NAME"
